{{- if and (not .Values.global.flowengineHA) (not .Values.global.nginxPlatformLegacyCompatibility) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: engine-config
  namespace: {{ .Release.Namespace }}
data:
  engine-nginx.conf: >
    
{{- if .Values.deployment.selector.iotbroker }}    
    location ~ ^/(iot-broker/actuator*) {
      deny all;
      return 404;
    }

    location /iot-broker {
        set $hostv $host;
        proxy_pass http://iotbrokerservice:19000/iot-broker;
        proxy_read_timeout 360s;

        proxy_set_header Host $hostv;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;

    }
{{- end }}
{{- if .Values.deployment.selector.apimanager }}
    location ~ ^/(api-manager/actuator*) {
      deny all;
      return 404;
    }

    location /api-manager {

    proxy_pass http://apimanagerservice:19100/api-manager;
    proxy_read_timeout 360s;

    proxy_set_header Host $host;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port 443;

    }
{{- end }}
{{- if .Values.deployment.selector.flowengine }}
      location ~ ^/nodered/.*/metrics {
          deny all;
          return 404;
      }

      location /nodered/ {
            proxy_pass  http://flowengineservice:5050/;
          proxy_read_timeout 360s;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Forwarded-For $remote_addr;
      }

    location ~ ^/(flowengine/actuator*) {
      deny all;
      return 404;
    }

      location /flowengine {
            proxy_pass  http://flowengineservice:20100;
          proxy_read_timeout 360s;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Forwarded-For $remote_addr;
      }
{{- end }}
{{- if .Values.deployment.selector.oauthserver }}
    location ~ ^/(oauth-server/actuator*) {
      deny all;
      return 404;
    }

    location /oauth-server {
            proxy_pass  http://oauthservice:21000/oauth-server;
            proxy_read_timeout 360s;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $remote_addr;
            
            proxy_redirect ~^http://oauthservice:21000(.+)$ https://$host$1;
        }
{{- end }}
{{- end }}
