{{- if and .Values.global.localStorageEnabled (not .Values.global.skipPersistenceDeployment) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pvs.logs }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
{{- if .Values.global.keepPersistence }}
{{- template "annotations.keepresources" }}
{{- end }}      
spec:
  storageClassName: {{ .Values.global.logStorageClassName }}
  capacity:
    storage: {{ .Values.global.logStoragesize }}
{{- if .Values.global.setNodesOnDeployments }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ .Values.global.nodeKey }}
          operator: In
          values:
          {{- range .Values.global.workerNodes }}
          - {{ .node }}
          {{- end }}
{{- end }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.global.localStoragePath }}/onesaitplatform/platform-logs
{{- end }}
