{{- if and .Values.global.localStorageEnabled (not .Values.global.skipPersistenceDeployment) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.keepPersistence }}
{{- template "annotations.keepresources" }}
{{- end }}    
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  volumeName: {{ .Values.persistence.pvs.logs }}
  storageClassName: {{ .Values.global.logStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.global.logStoragesize }}
{{- end }}
