{{- if and .Values.deployment.selector.streamsets (not .Values.global.skipPersistenceDeployment) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-pvc-data
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.keepPersistence }}
{{- template "annotations.keepresources" }}
{{- end }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.global.localStorageEnabled }}
  volumeMode: Filesystem
  volumeName: {{ .Values.persistence.pvs.dataflowdata }}
{{- end }}
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.streamsets.storage.dataSize }}
{{- end }}
