{{- if .Values.global.deployQuasar }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onesait-platform.quasar.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    run: {{ include "onesait-platform.quasar.name" . }}
    k8s-app: {{ include "onesait-platform.quasar.name" . }}
spec:
  ports:
  - port: {{ .Values.quasar.service.port }}
    protocol: TCP
    targetPort: {{ .Values.quasar.service.targetPort }}
  selector:
    app: {{ include "onesait-platform.quasar.name" . }}
  type: {{ .Values.quasar.service.type }}
  sessionAffinity: None
{{- end }}
