apiVersion: v1
kind: Secret
metadata:
  name: configdb-data
type: Opaque
stringData:
  configdb-data.conf: >
    [client]
    
    user = {{ .Values.global.env.configDbUser }}
    
    password = {{ .Values.global.env.configDbPass }}
    
    host = {{ .Values.global.env.configDbHost }}