apiVersion: v1
kind: Secret
metadata:
  name: onesait-secret
type: Opaque
stringData:
  REALTIMEDBPASS: "{{ .Values.global.env.realtimeDbPass }}"
  CONFIGDBPASS: "{{ .Values.global.env.configDbPass }}"
  SCHEDULERDBBPASS: "{{ .Values.global.env.schedulerDbPass }}"
