{{- if .Values.global.deployConfigInit }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onesait-platform.configinit.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "onesait-platform.configinit.name" . }}
    group: {{ .Values.global.groupName }}
spec:
  replicas: {{ .Values.global.replicaInitCount }}
  selector:
    matchLabels:
      app: {{ include "onesait-platform.configinit.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onesait-platform.configinit.name" . }}
    spec:
{{- if .Values.global.affinityNodeRules }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: app
                operator: NotIn
                values:
                - {{ include "onesait-platform.configinit.name" . }}
            weight: 100
{{ end }}
{{- if .Values.global.setNodesOnDeployments }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range .Values.global.workerNodes }}
                - {{ .node }}
                {{- end }}

{{ end }}
      containers:
      - name: {{ include "onesait-platform.configinit.name" . }}
        image: "{{ .Values.configinit.image.repository }}:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.configinit.image.pullPolicy }}
        env:
        - name: LOADELASTICDB
          value: "{{ .Values.configinit.env.loadElasticDb }}"
        - name: LOADMONGODB
          value: "{{ .Values.configinit.env.loadMongoDb }}"
        - name: SERVER_NAME
          value: "{{ .Values.global.env.serverName }}"
        - name: CONFIGDBMASTERURL
          value: "{{ .Values.global.env.configDbMasterUrl }}{{.Values.configinit.env.configDbMasterUrlCreateIfNotExists}}"
        - name: CONFIGDBURL
          value: "{{ .Values.global.env.configDbUrl }}"
        - name: CONFIGDBUSER
          value: "{{ .Values.global.env.configDbUser }}"
        - name: CONFIGDBPASS
          valueFrom:
            secretKeyRef:
              key: CONFIGDBPASS
              name: onesait-secret
        - name: REALTIMEDBUSER
          value: "{{ .Values.global.env.realtimeDbUser }}"
        - name: REALTIMEDBPASS
          valueFrom:
            secretKeyRef:
              key: REALTIMEDBPASS
              name: onesait-secret
        - name: REALTIMEDBSERVERS
          value: "{{ .Values.global.env.realtimeDbServers }}"
        - name: REALTIMEDBNAME
          value: "{{ .Values.global.env.realtimeDbName }}"
        - name: UPDATE_MODE_MULTITENANT
          value: "{{ .Values.configinit.env.multitenantMode }}"
        - name: ONESAIT_PROPERTIES
          value: "{{ .Values.configinit.env.onesaitProperties }}"
        ports:
        - containerPort: 21000
          name: 21000tcp210002
          protocol: TCP
{{- if .Values.global.limitsEnabled }}
        resources:
          limits:
            cpu: "500m"
            memory: "2Gi"
          requests:
            cpu: "1m"
            memory: "1Mi"
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
{{- end }}
