{{- if and .Values.global.localStorageEnabled (not .Values.global.skipPersistenceDeployment) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pvs.controlpanel }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
{{- if .Values.global.keepPersistence }}
{{- template "annotations.keepresources" }}
{{- end }}  
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  capacity:
    storage: {{ .Values.controlpanel.storage.size }}
{{- if .Values.global.setNodesOnDeployments }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ .Values.global.nodeKey }}
          operator: In
          values:
          {{- range .Values.global.workerNodes }}
          - {{ .node }}
          {{- end }}
{{- end }}
  accessModes:
{{- if .Values.global.webProjectsSharedPvc }}
    - ReadWriteMany
{{- else }}
    - ReadWriteOnce
{{- end }}
  hostPath:
    path: {{ .Values.global.localStoragePath }}/onesaitplatform/webprojects
{{- end }}
