apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controlpanel-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - {{ .Values.controlpanel.storage.accessMode }}
{{- if .Values.global.localStorageEnabled }}
  volumeMode: Filesystem
  volumeName: controlpanel-pv-volume
{{- end }}
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.controlpanel.storage.size }}
