apiVersion: v1
kind: Service
metadata:
  name: {{ include "onesait-platform.controlpanel.name" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    run: {{ include "onesait-platform.controlpanel.name" . }}
    k8s-app: {{ include "onesait-platform.controlpanel.name" . }}
spec:
  ports:
  - port: {{ .Values.controlpanel.service.port }}
    protocol: TCP
    targetPort: {{ .Values.controlpanel.service.targetPort }}
  selector:
    app: {{ include "onesait-platform.controlpanel.name" . }}
  type: {{ .Values.controlpanel.service.type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
