# Global Variables
global:
  groupName: onesait-platform
  storageClassName: standard-csi
  storageClassProvisioned: false
  logStorageClassName: standard-csi
  localStorageEnabled: false
  hostAliasEnabled: true
  image:
    tag: 6.0.0-ce
  env:
    serverName: "example.onesaitplatform.com"
    ipHost: "172.25.5.4"
    kafkaEnabled: "false"
    ingressHostName: example.onesaitplatform.com
