# Global Variables
global:
  groupName: onesait-platform
  storageClassName: standard-csi
  storageClassProvisioned: false
  localStorageEnabled: false
  image:
    tag: 6.0.0-ce
  env:
    serverName: "example.onesaitplatform.com"
    kafkaEnabled: "false"
    avdIdentityMngAPIKey: "d4d173323edb49cb8df923182863fda5"