# Global Variables
global:
  groupName: onesait-platform
  storageClassName: standard-csi
  storageClassProvisioned: false
  logStorageClassName: standard-csi
  localStorageEnabled: false
  image:
    tag: 5.2.0-ce
  env:
    serverName: "example.onesaitplatform.com"
    kafkaEnabled: "false"
    ingressHostName: example.onesaitplatform.com
