apiVersion: v1
kind: Secret
metadata:
  name: onesait-minio-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: "{{ .Values.minio.accesskey }}"
  MINIO_ROOT_PASSWORD: "{{ .Values.minio.secretkey }}"