apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onesait-platform.zookeeper.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "onesait-platform.zookeeper.name" . }}
    group: {{ .Values.global.groupName }}
spec:
  replicas: {{ .Values.global.replicaInitCount }}
  selector:
    matchLabels:
      app: {{ include "onesait-platform.zookeeper.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onesait-platform.zookeeper.name" . }}
    spec:
{{- if .Values.global.affinityNodeRules }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "onesait-platform.zookeeper.name" . }}
            topologyKey: "kubernetes.io/hostname"
{{ end }}
{{- if .Values.global.setNodesOnDeployments }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range .Values.global.workerNodes }}
                - {{ .node }}
                {{- end }}

{{ end }}
      containers:
      - name: {{ include "onesait-platform.zookeeper.name" . }}
        image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
        imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
{{- if .Values.global.healthChecksEnabled }}
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 100
          periodSeconds: 5
          successThreshold: 2
          tcpSocket:
            port: {{ .Values.zookeeper.service.targetPort }}
          timeoutSeconds: 2
{{- end }}
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "{{ .Values.zookeeper.env.zookeperClientPort }}"
        ports:
        - containerPort: {{ .Values.zookeeper.service.targetPort }}
          name: 2181tcp2181
          protocol: TCP
{{- if .Values.global.limitsEnabled }}
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "1m"
            memory: "1Mi"
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
