# Global Variables
global:
  groupName: onesait-platform
  replicaCount: 0
  replicaInitCount: 1
  limitsEnabled: true
  healthChecksEnabled: true
  keepPersistence: true
  skipPersistenceDeployment: false
  localStorageEnabled: false
  localStoragePath: /datadrive
  storageClassName: managed-premium
  storageClassProvisioned: false
  logStorageClassName: Azurefile
  logStoragesize: 20Gi
  storageClassOnPvcsEnabled: false
  sideCarContainersEnabled: false
  loadbalancerExternalTrafficPolicyClusterEnabled: false
  streamsetsSdcSecurityContext: false
  flowengineSecurityContext: false
  nginxConfPersistenceEnabled: false
  nginxConfigAsConfigMap: true
  nginxControllerPresent: true
  nginxPlatformLegacyCompatibility: false
  setIngressTLS: true
  tlsIngressEnabled: true
  certificateAwsArn: none
  webProjectsSharedPvc: false
  deployQuasar: false
  configDbType: mariadb
  kafkaAuthUrl: false
  gcpFilesEnabled: false
  prestoEnabled: false
  externalDatabase: false
  affinityNodeRules: false
  setNodesOnDeployments: false
  nodeKey: kubernetes.io/hostname
  workerNodes:
    - node: worker
    - node: worker2
  image:
    tag: 5.2.0-ce
  env:
    serverName: "localhost"
    configDbMasterUrl: "jdbc:mysql://configdb:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true"
    configDbUrl: "jdbc:mysql://configdb:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&autoReconnect=true&nullDatabaseMeansCurrent=true"
    schedulerDbUrl: "jdbc:mysql://configdb:3306/onesaitplatform_scheduler?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true"
    configDbUser: "root"
    configDbPass: "changeIt!"
    configDbDriver: "com.mysql.cj.jdbc.Driver"
    configDbDialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
    realtimeDbUser: "platformadmin"
    realtimeDbPass: "0pen-platf0rm-2018!"
    schedulerDbUser: "root"
    schedulerDbPass: "changeIt!"
    schedulerDbDriver: "com.mysql.cj.jdbc.Driver"
    schedulerDbDialect: "org.hibernate.dialect.MySQL5Dialect"
    quartzDriver: "org.quartz.impl.jdbcjobstore.StdJDBCDelegate"
    realtimeDbWriteConcern: "UNACKNOWLEDGED"
    realtimeDbServers: "realtimedb:27017"
    realtimeDbName: "onesaitplatform_rtdb"
    kafkaEnabled: false
    kafkaHost: kafkaservice
    hzServiceDiscoveryStrategy: zookeeper
    hzZookeeperUrl: zookeeper:2181
    ingressHostName: example.onesaitplatform.com
    auditGlobalNotify: "false"
    elasticEnabled: false
    httpLogLevel: "INFO"
    opendataPath: "opendata"

# Variables for configdb deployment/service/storage
configdb:
  nameOverride: configdb
  image:
    repository: onesaitplatform/configdb
    tag: mariadb
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
    targetPort: 3306
  storage:
    size: 1Gi

# Variables for realtimedb deployment/service/storage
realtimedb:
  nameOverride: realtimedb
  image:
    repository: onesaitplatform/realtimedb
    tag: "5.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017
  storage:
    size: 30Gi
  customWiredTiger: false
  wiredTigerSizeGB: 1 

# Variables for quasar deployment/service
quasar:
  nameOverride: quasar
  image:
    repository: onesaitplatform/quasar
    tag: 14
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 10800
    targetPort: 10800
  env:
    realtimeDbServers: realtimedb:27017
    authDb: "admin"
    authParams: "platformadmin:0pen-platf0rm-2018!@"

# Variables for zookeeper deployment/service
zookeeper:
  nameOverride: zookeeper
  image:
    repository: onesaitplatform/zookeeper-secured
    tag: cp-6.1.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 2181
    targetPort: 2181
  env:
    zookeperClientPort: "2181"
  storage:
    dataSize: 5Gi
    logsSize: 5Gi

# Variables for kafka deployment/service
kafka:
  nameOverride: kafkaservice
  image:
    repository: onesaitplatform/kafka-secured
    tag: cp-6.1.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    tcp:
      port: 9092
      targetPort: 9092
    tls:
      port: 9095
      targetPort: 9095
  env:
    kafkaListeners: "SASL_PLAINTEXT://:9095,PLAINTEXT://:9092"
    kafkaOffsetTopicReplFactor: "1"
    kafkaZookeeperConnect: "zookeeper:2181"
    kafkaAdvertisedListeners: "SASL_PLAINTEXT://kafkaservice:9095,PLAINTEXT://kafkaservice:9092"
    kafkaSuperUsers: "User:admin"
    kafkaLogDirs: "/var/lib/kafka/data"
    serverName: "localhost"
    authUrl: "http://iotbrokerservice.onesaitplatform:19000/iot-broker/rest/"
  storage:
    size: 21Gi
    logsSize: 10Gi

# Variables for elasticdb deployment/service/storage
elasticdb:
  nameOverride: elasticdb
  image:
    repository: onesaitplatform/elasticdb
    tag: 7.9.3
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    tcp1:
      port: 9200
      targetPort: 9200
    tcp2:
      port: 9300
      targetPort: 9300
  storage:
    size: 10Gi

# Variables for configinit deployment
configinit:
  nameOverride: configinit
  image:
    repository: onesaitplatform/configinit
    pullPolicy: Always
  env:
    loadElasticDb: "false"
    loadMongoDb: "false"
    loadGraylogDb: "false"
    loadMailConfig: "false"
    multitenantMode: "false"
    createDataFlowInstanceVertical: "false"
    configDbMasterUrlCreateIfNotExists: "&createDatabaseIfNotExist=true"
    rtdbExecutionTimeout: 10000
    rtdbQueriesLimit: 2000
    mongoSocketTimeout: 5000
    mongoConnectTimeout: 30000
    mongoWaitTime: 5000
    mongoPoolSize: 100
    mongoSslEnabled: false
    iotBrokerTimeout: 60000
    onesaitProperties:
    loadTestData: false

# Variables for controlpanel deployment
controlpanel:
  nameOverride: controlpanelservice
  image:
    repository: onesaitplatform/controlpanel
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 18000
    targetPort: 18000
  env:
    capthaOn: "false"
    ksqlEnable: "false"
    streamsetsSdcVersion: "3.18.1"
    tfaEnabled: "false"
    authProvider: "configdb"
    ldapAdminDn: ""
    ldapAdminPassword: ""
    ldapAdminWhitelist: "administrator,admin"
    ldapAuthRegex: "(.*)"
    ldapBaseDn: "OU=''"
    ldapDefaultRole: "ROLE_USER"
    ldapGroupWhitelist:
    ldapIgnorePartialResult: "false"
    ldapImportUsers: "true"
    ldapRolesMemberAtt: ""
    ldapUrl: ""
    multitenancyEnabled: "false"
    notebookPlatformSSO: "true"
    onesaitProperties: >-
      {"onesaitplatform":{"webproject":{"rootfolder":{"path":"/opt/bitnami/nginx/webprojects/"}}}}
  storage:
    accessMode: ReadWriteOnce
    size: 2Gi
    prestoSize: 2Gi

# Variables for cacheserver deployment
cacheserver:
  nameOverride: cacheservice
  image:
    repository: onesaitplatform/cacheservice
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 20001
    targetPort: 20001
  env:
    onesaitProperties:

# Variables for monitoringuiservice deployment/service
monitoringui:
  nameOverride: monitoringuiservice
  image:
    repository: onesaitplatform/monitoringui
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 18100
    targetPort: 18100
  env:
    onesaitProperties:

# Variables for load balancer / reverse proxy deployment/service
# IMPORTANT: Use mainline tag for all modules deployed
loadbalancer:
  nameOverride: loadbalancer
  image:
    repository: onesaitplatform/loadbalancer
    tag: 5.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    hostIp: localhost
    http:
      port: 9443
      targetPort: 9443
    flowengine:
      port: 19999
      targetPort: 19999
  storage:
    size: 5Gi

# Variables for ingress
loadbalanceringress:
  nameOverride: loadbalanceringress

