{{- if and (.Values.global.nginxConfigAsConfigMap) (not .Values.global.nginxPlatformLegacyCompatibility) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: loadbalancer-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: >
    server_names_hash_bucket_size 128;

    server {
        listen 9443;
        server_name _;

        include /opt/bitnami/nginx/conf/server_blocks/engine/*;
        include /opt/bitnami/nginx/conf/server_blocks/intelligence/*;

        add_header Strict-Transport-Security "max-age=31536000" always;

        proxy_busy_buffers_size 512k;
        proxy_buffers 4 512k;
        proxy_buffer_size 256k;
        
        location = / {
             return 301 http://$host/controlpanel;
        }

        location ~ ^/(controlpanel/actuator*) {
             return 301 http://$host/controlpanel;
        }

    location /controlpanel {
        proxy_pass http://controlpanelservice:18000/controlpanel;
        proxy_read_timeout 360s;

        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_redirect ~^http://controlpanelservice:18000(.+)$ https://$host$1;

        proxy_set_header Host $host;
    }

      location /monitoring {
            proxy_pass  http://monitoringuiservice:18100/monitoring;
          proxy_read_timeout 360s;
          proxy_redirect ~^http://(.+)$ https://$1;
          proxy_set_header Host $host;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Forwarded-For $remote_addr;
      }

      location /web {
            alias /opt/bitnami/nginx/webprojects;
      }
    }

{{- end }}