{{- if .Values.global.nginxConfigAsConfigMap }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: loadbalancer-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: >
    server {
        listen 8443 ssl;
        server_name _;

      include /opt/bitnami/nginx/conf/server_blocks/api/*;
      include /opt/bitnami/nginx/conf/server_blocks/engine/*;
      include /opt/bitnami/nginx/conf/server_blocks/intelligence/*;
      include /opt/bitnami/nginx/conf/server_blocks/tools/*;
      include /opt/bitnami/nginx/conf/server_blocks/opendata/*;
      include /opt/bitnami/nginx/conf/server_blocks/things/*;
      include /opt/bitnami/nginx/conf/server_blocks/log/*;

      ssl_certificate /tmp/tls.crt;
      ssl_certificate_key /tmp/tls.key;

    ssl_protocols SSLv2 SSLv3 TLSv1.3 TLSv1.2;

    ssl_session_cache    shared:SSL:1m;

    ssl_session_timeout  5m;

    ssl_session_tickets off;

    ssl_ciphers
    TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-AES256-CCM8:ECDHE-ECDSA-ARIA256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-CCM:ECDHE-ECDSA-AES128-CCM8:ECDHE-ECDSA-ARIA128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ARIA256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ARIA128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-CCM:DHE-RSA-AES256-CCM8:DHE-RSA-ARIA256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-CCM:DHE-RSA-AES128-CCM8:DHE-RSA-ARIA128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384;

    ssl_prefer_server_ciphers on;

    ssl_ecdh_curve X25519:secp521r1:secp384r1;

        add_header Strict-Transport-Security "max-age=31536000" always;

    location /controlpanel {
      set $hostv "controlpanelservice:18000";
    proxy_pass http://controlpanelservice:18000/controlpanel;

    proxy_read_timeout 360s;


    proxy_http_version 1.1;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header X-Forwarded-Proto http;

          proxy_redirect ~^http://controlpanelservice:18000(.+)$ https://$host$1;

          if ($uri ~ "^.*(swagger-ui|api-docs).*"){
            set $hostv $http_host;
          }

        proxy_set_header Host $hostv;
    }

      location /monitoring {
            proxy_pass  http://monitoringuiservice:18100/monitoring;
          proxy_read_timeout 360s;
    proxy_redirect ~^http://monitoringuiservice:18100(.+)$ https://$host$1;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Forwarded-For $remote_addr;
      }

      location /web {
            alias /usr/local/webprojects;
      }

    }


    server {
        listen 9443;
        server_name _;

        include /opt/bitnami/nginx/conf/server_blocks/api/*;
        include /opt/bitnami/nginx/conf/server_blocks/engine/*;
        include /opt/bitnami/nginx/conf/server_blocks/intelligence/*;
        include /opt/bitnami/nginx/conf/server_blocks/tools/*;
        include /opt/bitnami/nginx/conf/server_blocks/opendata/*;
        include /opt/bitnami/nginx/conf/server_blocks/things/*;
        include /opt/bitnami/nginx/conf/server_blocks/log/*;
        
        add_header Strict-Transport-Security "max-age=31536000" always;

    location /controlpanel {
      set $hostv "controlpanelservice:18000";
    proxy_pass http://controlpanelservice:18000/controlpanel;

    proxy_read_timeout 360s;


    proxy_http_version 1.1;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header X-Forwarded-Proto http;

          proxy_redirect ~^http://controlpanelservice:18000(.+)$ https://$host$1;

          if ($uri ~ "^.*(swagger-ui|api-docs).*"){
            set $hostv $http_host;
          }

        proxy_set_header Host $hostv;
    }

      location /monitoring {
            proxy_pass  http://monitoringuiservice:18100/monitoring;
          proxy_read_timeout 360s;
    proxy_redirect ~^http://monitoringuiservice:18100(.+)$ https://$host$1;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Forwarded-For $remote_addr;
      }

      location /web {
            alias /usr/local/webprojects;
      }
    }
{{- end }}
