{{- if and (not .Values.global.skipIngressDeployment) (ne .Values.global.cloudProvider "aws") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onesait-platform.ingress.name" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.nginxControllerPresent }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
{{- end }}
spec:
{{- if .Values.global.setIngressTLS }}
  tls:
  - hosts:
    - {{ .Values.global.env.ingressHostName }}
    secretName: loadbalancersecret
{{- end }}    
  rules:
  - host: {{ .Values.global.env.ingressHostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "onesait-platform.loadbalancer.name" . }}
            port:
              number: {{ .Values.loadbalancer.service.http.port }}
{{- end }}
