{{- if .Values.global.nginxConfPersistenceEnabled }}
{{- if .Values.global.localStorageEnabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loadbalancer-pv-volume
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  capacity:
    storage: {{ .Values.loadbalancer.storage.size }}
{{- if .Values.global.setNodesOnDeployments }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          {{- range .Values.global.workerNodes }}
          - {{ .node }}
          {{- end }}
{{- end }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.global.localStoragePath }}/onesaitplatform/loadbalancer
{{- end }}
{{- end }}
