{{- if .Values.global.nginxConfPersistenceEnabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loadbalancer-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - {{ .Values.controlpanel.storage.accessMode }}
{{- if .Values.global.localStorageEnabled }}
  volumeMode: Filesystem
  volumeName: {{ .Values.persistence.pvs.loadbalancer }}
{{- end }}
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.controlpanel.storage.size }}
{{- end }}
