# Global Variables
global:
  groupName: onesait-platform
  replicaCount: 1
  limitsEnabled: true
  localStorageEnabled: false
  localStoragePath: /datadrive
  healthChecksEnabled: true
  sideCarContainersEnabled: false
  keepPersistence: true
  skipPersistenceDeployment: false
  storageClassName: managed-premium
  storageClassProvisioned: false
  logStorageClassName: Azurefile
  logStoragesize: 20Gi
  storageClassOnPvcsEnabled: false
  flowengineSecurityContext: false
  nginxPlatformLegacyCompatibility: false
  affinityNodeRules: false
  setNodesOnDeployments: false
  nodeKey: kubernetes.io/hostname
  workerNodes:
    - node: worker
    - node: worker2
  image:
    tag: 5.2.0-ce
  env:
    serverName: "localhost"
    configDbMasterUrl: "jdbc:mysql://configdb:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true"
    configDbUrl: "jdbc:mysql://configdb:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&autoReconnect=true&nullDatabaseMeansCurrent=true"
    configDbUser: "root"
    configDbPass: "changeIt!"
    configDbDriver: "com.mysql.cj.jdbc.Driver"
    configDbDialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
    realtimeDbUser: "platformadmin"
    realtimeDbPass: "0pen-platf0rm-2018!"
    realtimeDbWriteConcern: "UNACKNOWLEDGED"
    realtimeDbServers: "realtimedb:27017"
    realtimeDbName: "onesaitplatform_rtdb"
    timeSeriesEnabled: "false"
    timeSeriesDbUser: "postgres"
    timeSeriesDbPass: "password"
    kafkaEnabled: "false"
    kafkaHost: kafkaservice
    kafkaBrokers: "kafkaservice:9095"
    hzServiceDiscoveryStrategy: zookeeper
    hzZookeeperUrl: zookeeper:2181
    auditGlobalNotify: "false"
    elasticEnabled: "false"
    httpLogLevel: "INFO"

deployment:
  selector:
    semanticinfbroker: true
    iotbroker: true
    apimanager: true
    flowengine: true
    oauthserver: true
    auditrouter: true

persistence:
    pvs:
      flowengine: flowengine-pv-volume

# Variables for semantic information broker deployment/service
semanticinfbroker:
  nameOverride: routerservice
  image:
    repository: onesaitplatform/router
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 20000
    targetPort: 20000
  env:
    onesaitProperties:
    notificationSubscriptionAttemps: 5
    notificationPoolSubscriptionNotificator: 50
    notificationPoolSubscription: 50
    opLogLevel: "INFO"
    queriesDefaultLimit: "2000"
    javaOpts:

# Variables for IoT broker deployment/service
iotbroker:
  nameOverride: iotbrokerservice
  image:
    repository: onesaitplatform/iotbroker
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 19000
    targetPort: 19000
  env:
    onesaitProperties:
    opLogLevel: "OFF"
    javaOpts:

# Variables for API manager deployment/service
apimanager:
  nameOverride: apimanagerservice
  image:
    repository: onesaitplatform/apimanager
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 19100
    targetPort: 19100
  env:
    onesaitProperties:

# Variables for flowengine deployment/service
flowengine:
  nameOverride: flowengineservice
  image:
    repository: onesaitplatform/flowengine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    nodered:
      port: 5050
      targetPort: 5050
    flowengine:
      port: 20100
      targetPort: 20100
    internalport:
      port: 10000
      targetPort : 10000
  env:
    onesaitProperties:
  storage:
    size: 5Gi

# Variables for oauth server deployment/service
oauthserver:
  nameOverride: oauthservice
  image:
    repository: onesaitplatform/oauthserver
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 21000
    targetPort: 21000
  env:
    authProvider: "configdb"
    ldapAdminDn: ""
    ldapAdminPassword: ""
    ldapAdminWhitelist: "administrator,admin"
    ldapAuthRegex: "(.*)"
    ldapBaseDn: "OU=''"
    ldapDefaultRole: "ROLE_USER"
    ldapGroupWhitelist:
    ldapIgnorePartialResult: "false"
    ldapImportUsers: "true"
    ldapRolesMemberAtt: ""
    ldapUrl: ""
    multitenancyEnabled: "false"
    onesaitProperties:

auditrouter:
  nameOverride: auditrouter
  image:
    repository: onesaitplatform/audit-router
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 20002
    targetPort: 20002
  env:
    onesaitProperties:
    notificationSubscriptionAttemps: 5
    notificationPoolSubscriptionNotificator: 50
    notificationPoolSubscription: 50
    opLogLevel: "INFO"
    javaOpts:
