# Global Variables
global:
  groupName: onesait-platform
  replicaCount: 1
  limitsEnabled: true
  localStorageEnabled: false
  localStoragePath: /datadrive
  healthChecksEnabled: true
  sideCarContainersEnabled: false
  keepPersistence: true
  skipPersistenceDeployment: false
  storageClassName: managed-premium
  storageClassProvisioned: false
  logStorageClassName: Azurefile
  logStoragesize: 20Gi
  storageClassOnPvcsEnabled: false
  flowengineSecurityContext: false
  nginxPlatformLegacyCompatibility: false
  affinityNodeRules: false
  setNodesOnDeployments: false
  nodeKey: kubernetes.io/hostname
  workerNodes:
    - node: worker
    - node: worker2
  image:
    tag: 6.2.0-ce
  env:
    serverName: "localhost"
    configDbMasterUrl: "jdbc:mysql://configdb:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true"
    configDbUrl: "jdbc:mysql://configdb:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&autoReconnect=true&nullDatabaseMeansCurrent=true"
    configDbUser: "root"
    configDbPass: "changeIt!"
    configDbDriver: "com.mysql.cj.jdbc.Driver"
    configDbDialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
    realtimeDbUser: "platformadmin"
    realtimeDbPass: "0pen-platf0rm-2018!"
    realtimeDbWriteConcern: "UNACKNOWLEDGED"
    realtimeDbServers: "realtimedb:27017"
    realtimeDbName: "onesaitplatform_rtdb"
    timeSeriesEnabled: "false"
    timeSeriesDbUser: "postgres"
    timeSeriesDbPass: "password"
    kafkaEnabled: "false"
    kafkaHost: kafkaservice
    kafkaBrokers: "kafkaservice:9095"
    hzServiceDiscoveryStrategy: zookeeper
    hzZookeeperUrl: zookeeper:2181
    auditGlobalNotify: "false"
    elasticEnabled: "false"
    opensearchEnabled: false
    avdIdentityMngEnabled: "true"
    avdIdentityMngAPIKey: "0dfd700d66884fa9b7a1c2d1ddcc901d"
    oauthSSOEnabled: "true"
    httpLogLevel: "INFO"

deployment:
  selector:
    semanticinfbroker: true
    iotbroker: true
    apimanager: true
    flowengine: true
    auditrouter: true

persistence:
    pvs:
      flowengine: flowengine-pv-volume

# Variables for semantic information broker deployment/service
semanticinfbroker:
  nameOverride: routerservice
  image:
    repository: onesaitplatform/router
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 20000
    targetPort: 20000
  env:
    onesaitProperties:
    notificationSubscriptionAttemps: 5
    notificationPoolSubscriptionNotificator: 50
    notificationPoolSubscription: 50
    opLogLevel: "INFO"
    queriesDefaultLimit: "2000"
    javaOptsDefault: true
    javaOpts:
  limits:
    cpu: "1000m"
    memory: "2500Mi"
  requests:
    cpu: "1m"
    memory: "1Mi"
  replicas: 1

# Variables for IoT broker deployment/service
iotbroker:
  nameOverride: iotbrokerservice
  image:
    repository: onesaitplatform/iotbroker
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 19000
    targetPort: 19000
  env:
    onesaitProperties:
    opLogLevel: "OFF"
    enableMetrics: "false"
    javaOptsDefault: true
    javaOpts:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "1m"
    memory: "1Mi"
  replicas: 1

# Variables for API manager deployment/service
apimanager:
  nameOverride: apimanagerservice
  image:
    repository: onesaitplatform/apimanager
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 19100
    targetPort: 19100
  env:
    onesaitProperties:
  limits:
    cpu: "750m"
    memory: "2Gi"
  requests:
    cpu: "1m"
    memory: "1Mi"
  replicas: 1

# Variables for flowengine deployment/service
flowengine:
  nameOverride: flowengineservice
  image:
    repository: onesaitplatform/flowengine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    nodered:
      port: 5050
      targetPort: 5050
    flowengine:
      port: 20100
      targetPort: 20100
    internalport:
      port: 10000
      targetPort : 10000
  env:
    onesaitProperties:
  storage:
    size: 5Gi
  limits:
    cpu: "500m"
    memory: "2Gi"
  requests:
    cpu: "1m"
    memory: "1Mi"
    
auditrouter:
  nameOverride: auditrouter
  image:
    repository: onesaitplatform/audit-router
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 20002
    targetPort: 20002
  env:
    onesaitProperties:
    notificationSubscriptionAttemps: 5
    notificationPoolSubscriptionNotificator: 50
    notificationPoolSubscription: 50
    opLogLevel: "INFO"
    javaOptsDefault: true
    javaOpts:
  limits:
    cpu: "500m"
    memory: "1800Mi"
  requests:
    cpu: "1m"
    memory: "1Mi"
  replicas: 1
