apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.presto.service.presto }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s_app: {{ .Values.presto.service.presto }}
spec:
  ports:
  - port: {{ .Values.presto.service.prestoServerPort }}
    name: tcp
    protocol: TCP
    targetPort: {{ .Values.presto.service.prestoServerPort }}
{{- if .Values.global.monitoring }} 
  - name: metrics
    port: {{ .Values.presto.service.metricsPort }}
    protocol: TCP
    targetPort: {{ .Values.presto.service.metricsPort }}
{{- end }}
  type: ClusterIP
  selector:
    app: {{ .Values.presto.service.prestoServerAppName }}