apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.presto.service.metastoreServerAppName }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s_app: {{ .Values.presto.service.metastoreServerAppName }}
spec:
  ports:
  - port: {{ .Values.presto.service.metastoreServerPort }}
    name: tcp
  type: ClusterIP
  selector:
    app: {{ .Values.presto.service.metastoreServerAppName }}