apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onesait-platform.advidentitymanager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "onesait-platform.advidentitymanager.name" . }}
    group: {{ .Values.global.groupName }}
spec:
  replicas: {{ .Values.global.replicaInitCount }}
  selector:
    matchLabels:
      app: {{ include "onesait-platform.advidentitymanager.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onesait-platform.advidentitymanager.name" . }}
    spec:
{{- if .Values.global.affinityNodeRules }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "onesait-platform.advidentitymanager.name" . }}
            topologyKey: {{ .Values.global.nodeKey }}
{{ end }}
{{- if .Values.global.setNodesOnDeployments }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.global.nodeKey }}
                operator: In
                values:
                {{- range .Values.global.workerNodes }}
                - {{ .node }}
                {{- end }}

{{ end }}
      containers:
      - name: {{ include "onesait-platform.advidentitymanager.name" . }}
        image: "{{ .Values.advidentitymanager.image.repository }}:{{ .Values.advidentitymanager.image.tag }}"
        imagePullPolicy: {{ .Values.advidentitymanager.image.pullPolicy }}
{{- if .Values.global.healthChecksEnabled }}
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 2
          tcpSocket:
            port: {{ .Values.advidentitymanager.service.targetPort }}
          timeoutSeconds: 2
{{- end }}
        env:
        - name: KEYCLOAK_FRONTEND_URL
          value: "https://{{ .Values.global.env.serverName }}/auth"
        - name: VIRTUAL_HOST
          value: "{{ .Values.global.env.serverName }}"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_DB
          value: "{{ .Values.advidentitymanager.env.dbVendor }}"
        - name: KC_DB_USERNAME
          value: "{{ .Values.advidentitymanager.env.dbUser }}"
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: CONFIGDBPASS
              name: onesait-secret
        - name: KC_DB_URL
          value: "{{ .Values.advidentitymanager.env.jdbcUrl }}"
        - name: JDBC_MASTER_URL
          value: "{{ .Values.global.env.configDbMasterUrl }}"
        - name: JDBC_CONFIG_URL
          value: "{{ .Values.global.env.configDbUrl }}"
        - name: KC_CONSOLE_LOG_LEVEL
          value: "{{ .Values.advidentitymanager.env.logLevel }}"
        - name: JAVA_OPTS_APPEND
          value: "{{ .Values.advidentitymanager.env.javaOptsAppend }}"
        - name: KEYCLOAK_ADMIN
          value: "{{ .Values.advidentitymanager.env.keycloakUser }}"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "{{ .Values.advidentitymanager.env.keycloakPassword }}"
        - name: API_KEY
          value: "{{ .Values.global.env.administratorAPIKey }}"
        - name: KC_HOSTNAME_ADMIN_URL
          value: "https://{{ .Values.global.env.serverName }}/auth"
        ports:
        - containerPort: {{ .Values.advidentitymanager.service.targetPort }}
          name: 8080tcp80802
          protocol: TCP
{{- if .Values.global.localStorageEnabled }}
        volumeMounts:
        - mountPath: /var/log/platform-logs
          name: logs
{{- end }}
{{- if .Values.global.limitsEnabled }}
        resources:
          limits:
            cpu: "{{ .Values.advidentitymanager.limits.cpu }}"
            memory: "{{ .Values.advidentitymanager.limits.memory }}"
          requests:
            cpu: "{{ .Values.advidentitymanager.requests.cpu }}"
            memory: "{{ .Values.advidentitymanager.requests.memory }}"
{{- end }}
      dnsPolicy: ClusterFirst
{{- if .Values.global.registryAuthEnabled }}
      imagePullSecrets:
      - name: platform-registry
{{- end }}      
      restartPolicy: Always
{{- if .Values.global.localStorageEnabled }}
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc
{{- end }}
