{{- if or (.Values.deployment.selector.dashboard) (.Values.deployment.selector.notebook) (.Values.deployment.selector.datacleaner) (.Values.deployment.selector.datalabeling) (.Values.deployment.selector.modelsmanager)}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: intelligence-config
  namespace: {{ .Release.Namespace }}
data:
  intelligence-nginx.conf: >

{{- if .Values.deployment.selector.dashboard }}
    location ~ ^/(dashboardengine/actuator*) {
        deny all;
        return 404;
    }

    location /dashboardengine/loginRest {
        proxy_pass http://dashboardengineservice:18300;
    }
    
    location /dashboardengine/dsengine/rest/solver {
        proxy_pass http://dashboardengineservice:18300;
    }

    location /dashboardengine/dsengine/solver {
        proxy_pass http://dashboardengineservice:18300;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade websocket;
        proxy_set_header Connection upgrade;
        proxy_read_timeout 86400;
    }

    location /dashboardengine {
        proxy_pass http://dashboardengineservice:18300/dashboardengine;
        proxy_read_timeout 360s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $remote_addr;
    }
{{- end }}
{{- if .Values.deployment.selector.notebook }}
    location /controlpanel/notebooks/app/ws {
        proxy_pass http://zeppelin:8080/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade websocket;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
{{- end }}

{{- end }}