apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.service.browserAppName }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s_app: {{ .Values.minio.service.browserAppName }}
spec:
  ports:
  - port: {{ .Values.minio.service.browserPort }}
    name: tcp
  type: ClusterIP
  selector:
    app: {{ .Values.minio.service.browserAppName }}
