apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.minio.service.consoles.console }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.minio.service.consoleAppName }}
      statefulset: {{ .Values.minio.service.consoles.console }}
  serviceName: {{ .Values.minio.service.consoles.console }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.minio.service.consoleAppName }}
        statefulset: {{ .Values.minio.service.consoles.console }}
    spec:
      terminationGracePeriodSeconds: 10
{{- if .Values.global.setNodesOnDeployments }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.global.nodeKey }}
                operator: In
                values:
                {{- range .Values.global.workerNodes }}
                - {{ .node }}
                {{- end }}

{{ end }}      
      containers:
        - name: {{ .Values.minio.service.consoles.console }}
          image: "{{ .Values.minio.image.consoleRepository }}:{{ .Values.minio.image.consoleTag }}"
          args:
            - server
          env:
            - name: CONSOLE_PBKDF_PASSPHRASE
              value: "SECRET"
            - name: CONSOLE_PBKDF_SALT
              value: "SECRET"
            - name: CONSOLE_MINIO_SERVER
              value: "http://{{ include "onesait-platform.minio.name" . }}:{{ .Values.minio.service.serverPort }}"
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "{{ .Values.minio.service.consoles.redirect.console }}"
          ports:
            - containerPort: {{ .Values.minio.service.consolePort }}
{{- if .Values.global.limitsEnabled }}
          resources:
            limits:
              cpu: "{{ .Values.minio.limits.cpu }}"
              memory: "{{ .Values.minio.limits.memory }}"
            requests:
              cpu: "{{ .Values.minio.requests.cpu }}"
              memory: "{{ .Values.minio.requests.memory }}"
{{- end }}
{{- if .Values.global.healthChecksEnabled }}
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 100
            periodSeconds: 5
            successThreshold: 2
            tcpSocket:
              port: {{ .Values.minio.service.consoleTargetPort }}
            timeoutSeconds: 10
{{- end }}