apiVersion: v1
kind: Service
metadata:
  name: {{ include "onesait-platform.minio.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s_app: {{ include "onesait-platform.minio.name" . }}
spec:
  ports:
  - port: {{ .Values.minio.service.serverPort }}
    name: tcp
  - port: {{ .Values.minio.service.ftp.port }}
    name: ftp
  type: ClusterIP
  selector:
    app: {{ include "onesait-platform.minio.name" . }}
