{{- if .Values.deployment.selector.iotbroker }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onesait-platform.iotbroker.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "onesait-platform.iotbroker.name" . }}
    group: {{ .Values.global.groupName }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "onesait-platform.iotbroker.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onesait-platform.iotbroker.name" . }}
    spec:
{{- if .Values.global.affinityNodeRules }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: app
                operator: NotIn
                values:
                - {{ include "onesait-platform.iotbroker.name" . }}
            weight: 100
{{ end }}
{{- if .Values.global.setNodesOnDeployments }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.global.nodeKey }}
                operator: In
                values:
                {{- range .Values.global.workerNodes }}
                - {{ .node }}
                {{- end }}

{{ end }}
      containers:
      - name: {{ include "onesait-platform.iotbroker.name" . }}
        image: "{{ .Values.iotbroker.image.repository }}:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.iotbroker.image.pullPolicy }}
{{- if .Values.global.healthChecksEnabled }}
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 2
          tcpSocket:
            port: {{ .Values.iotbroker.service.targetPort }}
          timeoutSeconds: 2
{{- end }}
        env:
        - name: HZ_SERVICE_DISCOVERY_STRATEGY
          value: "{{ .Values.global.env.hzServiceDiscoveryStrategy }}"
        - name: HZ_ZOOKEEPER_URL
          value: "{{ .Values.global.env.hzZookeeperUrl }}"
        - name: AUDITGLOBALNOTIFY
          value: "{{ .Values.global.env.auditGlobalNotify }}"
        - name: SERVER_NAME
          value: "{{ .Values.global.env.serverName }}"
        - name: KAFKAENABLED
          value: "{{ .Values.global.env.kafkaEnabled }}"
        - name: KAFKAHOST
          value: "{{ .Values.global.env.kafkaHost }}"
        - name: KAFKABROKERS
          value: "{{ .Values.global.env.kafkaBrokers }}"
        - name: HTTP_LOG_LEVEL
          value: "{{ .Values.global.env.httpLogLevel }}"
        - name: CONFIGDBMASTERURL
          value: "{{ .Values.global.env.configDbMasterUrl }}"
        - name: CONFIGDBURL
          value: "{{ .Values.global.env.configDbUrl }}"
        - name: CONFIGDBUSER
          value: "{{ .Values.global.env.configDbUser }}"
        - name: CONFIGDBPASS
          valueFrom:
            secretKeyRef:
              key: CONFIGDBPASS
              name: onesait-secret
        - name: CONFIGDB_DRIVER
          value: "{{ .Values.global.env.configDbDriver }}"
        - name: CONFIGDB_DIALECT
          value: "{{ .Values.global.env.configDbDialect }}"              
        - name: REALTIMEDBUSER
          value: "{{ .Values.global.env.realtimeDbUser }}"
        - name: REALTIMEDBPASS
          valueFrom:
            secretKeyRef:
              key: REALTIMEDBPASS
              name: onesait-secret
        - name: ONESAIT_PROPERTIES
          value: "{{ .Values.iotbroker.env.onesaitProperties }}"
        - name: OP_LOG_LEVEL
          value: "{{ .Values.iotbroker.env.opLogLevel }}"
        ports:
        - containerPort: {{ .Values.iotbroker.service.targetPort }}
          name: 19000tcp190002
          protocol: TCP
{{- if .Values.global.localStorageEnabled }}
        volumeMounts:
        - mountPath: /var/log/platform-logs
          name: logs
{{- end }}
{{- if .Values.global.limitsEnabled }}
        resources:
          limits:
            cpu: "500m"
            memory: "1.5Gi"
          requests:
            cpu: "1m"
            memory: "1Mi"
{{- end }}
      dnsPolicy: ClusterFirst    
      restartPolicy: Always
{{- if .Values.global.localStorageEnabled }}
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc
{{- end }}
{{- end }}
