apiVersion: v2
name: onesaitplatform-ce-minio-chart
description: MinIO S3 storage chart for k8s
home: https://cicd.onesaitplatform.com/gitlab/onesait-platform/onesaitplatform-operator.git
type: application
version: "6.2.0-ce"
appVersion: "0.43.1"
maintainers:
  - name: Onesait Platform
    email: support@onesaitplatform.com
    url: lab.onesaitplatform.com
icon: https://avatars1.githubusercontent.com/u/44359141?s=460&v=4
