apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.global.localStorageEnabled }}
  volumeMode: Filesystem
  volumeName: kafka-pv-volume
{{- end }}
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.kafka.storage.size }}
