apiVersion: v1
kind: Service
metadata:
  name: {{ include "onesait-platform.kafka.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    run: {{ include "onesait-platform.kafka.name" . }}
    k8s-app: {{ include "onesait-platform.kafka.name" . }}
spec:
  ports:
  - name: tcp
    port: {{ .Values.kafka.service.tcp.port }}
    protocol: TCP
    targetPort: {{ .Values.kafka.service.tcp.targetPort }}
  - name: tls
    port: {{ .Values.kafka.service.tls.port }}
    protocol: TCP
    targetPort: {{ .Values.kafka.service.tls.targetPort }}
  selector:
    app: {{ include "onesait-platform.kafka.name" . }}
  type: {{ .Values.kafka.service.type }}
  sessionAffinity: None
