apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onesait-platform.elasticdb.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "onesait-platform.elasticdb.name" . }}
    group: {{ .Values.global.groupName }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "onesait-platform.elasticdb.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onesait-platform.elasticdb.name" . }}
    spec:
{{- if .Values.global.setNodesOnDeployments }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range .Values.global.workerNodes }}
                - {{ .node }}
                {{- end }}

{{ end }}
      containers:
      - name: {{ include "onesait-platform.elasticdb.name" . }}
        image: "{{ .Values.elasticdb.image.repository }}:{{ .Values.elasticdb.image.tag }}"
        imagePullPolicy: {{ .Values.elasticdb.image.pullPolicy }}

{{- if .Values.global.healthChecksEnabled }}
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 100
          periodSeconds: 5
          successThreshold: 2
          tcpSocket:
            port: {{ .Values.elasticdb.service.tcp1.targetPort }}
          timeoutSeconds: 2
{{- end }}
        ports:
        - containerPort: {{ .Values.elasticdb.service.tcp1.targetPort }}
          name: 9200tcp92002
          protocol: TCP
        - containerPort: {{ .Values.elasticdb.service.tcp2.targetPort }}
          name: 9300tcp93002
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticdb-data
{{- if (not .Values.global.localStorageEnabled) }}
          subPath: elasticdb
{{- end }}          
{{- if .Values.global.limitsEnabled }}
        resources:
          limits:
            cpu: "500m"
            memory: "3Gi"
          requests:
            cpu: "1m"
            memory: "1Mi"
{{- end }}
      dnsPolicy: ClusterFirst
{{- if .Values.global.sideCarContainersEnabled }}
      initContainers:
       - name: volume-mount
         image: busybox
         command: ["sh", "-c", "chmod 777 /usr/share/elasticsearch/data"]
         volumeMounts:
         - name: elasticdb-data
           mountPath: /usr/share/elasticsearch/data
         resources:
           limits:
             cpu: "1"
             memory: "500Mi"
           requests:
             cpu: "1m"
             memory: "1Mi"
{{- end }}
      restartPolicy: Always
      volumes:
      - name: elasticdb-data
        persistentVolumeClaim:
          claimName: elasticdb-pvc
