{{- if .Values.global.deploySchedulerDb }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedulerdb-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.global.localStorageEnabled }}
  volumeMode: Filesystem
  volumeName: schedulerdb-pv-volume
{{- end }}
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.schedulerdb.storage.size }}
{{- end }}
